### ISSUE TITLE
Can u share a video or something for your app

### ISSUE THREAD

**Issue by johnfelipe** [reelyactive/barnowl-aruba#1]
I want to contribute with my campus, will be an academic project, is possible your guide?

**Comment by jeffyactive** [comment]
Thanks for your interest @johnfelipe.  I've added in the README a link to our [Configure an Aruba Instant AP](https://reelyactive.github.io/diy/aruba-instant-config/) tutorial, and you might find helpful [this video](https://customer-p1ws0amdtp68qh97.cloudflarestream.com/c6eafda1214b5518d74d568b9451cd65/watch) which shows some screenshots with Aruba AP integration.

We'd be happy to collaborate with you on your academic project.  Please [contact reelyActive](https://www.reelyactive.com/contact/) by e-mail and we'll be happy to discuss!

**Comment by johnfelipe** [comment]
How can install locally all environment?
Aruba central
Third party apps
Do I need licence for that?

**Comment by jeffyactive** [comment]
You can install Pareto Anywhere locally (free of cost, MIT License), which includes barnowl-aruba, by following the tutorial: [Run Pareto Anywhere on a PC](https://reelyactive.github.io/diy/pareto-anywhere-pc/).

If you have an Aruba AP with Instant version >= 8.8, then you can already forward and process data by following our [Configure an Aruba Instant AP](https://reelyactive.github.io/diy/aruba-instant-config/) tutorial.

If you want to use Aruba Central, you're better to check with your local Aruba representative and/or IT department about licenses.  That is well beyond our scope.

Try with Instant v8.10 first, if you can.  Good luck!
