### ISSUE TITLE
is possible have a video or url tryout with an enviroment for anlytics

### ISSUE THREAD

**Issue by johnfelipe** [reelyactive/barnowl-aruba#2]
In my campus is need collect for example use of wifi, all AP have OEM from ARUBA, i do something, with a fake dataset or sheecheat

https://drive.google.com/file/d/1e0pIxNXr-kpVb2pnbdXsmJhsOljuAPcW/view?usp=drivesdk

but we need to know how collect via API from ARUBA that %

**Comment by jeffyactive** [comment]
Gracias por el video @johnfelipe, my Spanish is just good enough to understand what you are trying to do.

Unfortunately, I don't think you'll be able to retrieve the % without a paid Analytics and Location Engine (ALE) license from Aruba: https://www.arubanetworks.com/assets/ds/DS_ALE.pdf

Our barnowl-aruba open source software only collects Bluetooth Low Energy data from Aruba APs using the Aruba IoT Interface.  It does not collect any WiFi data.  Try searching for "Aruba ALE" on GitHub and to find projects closer to what you need, like this: https://github.com/esvanegas/arubaale-api-connection

Good luck!

**Comment by johnfelipe** [comment]
Ok, OK, can u share me a video or tryout for show to my teacher?
