### ISSUE TITLE
Any way to get the the distance of a transmitter?

### ISSUE THREAD

**Issue by svenvanhees** [reelyactive/barnowl-aruba#5]
Hi,

Is there any way to to get the distance property from the Aruba telemetry report? While posting the json directly from the gateway, I see there is a distance property and could really use that for my use case.

Love your work btw!

**Comment by jeffyactive** [comment]
Hi @svenvanhees,

Where do you see a distance property in the Aruba IoT WebSocket telemetry reports?  I've passed through all the BLE/WiFi Telemetry and BLE Data reports using an AP running AOS 8.10+ and the only reference to distance that I see is in the advanced configuration ("Report devices that are within X meters of the beacon").

Nonetheless, we've just pushed v1.2.0 which processes the Telemetry reports (including the WiFi reports) more thoroughly.

Can you elaborate more on what you observe/expect with regards to a distance property?

Thanks for the kind words!

**Comment by svenvanhees** [comment]
Hello!

I figured out I was confusing the Aruba with a Minew receiver. The Minew did show a estimated distance. Thanks anyway for responding.
