### ISSUE TITLE
Not receiving displacement events

### ISSUE THREAD

**Issue by svenvanhees** [reelyactive/barnowl-aruba#6]
I have setup a test situation with two Aruba 303 AP's. Both are connecting with a websocket to the Barnowl Aruba instance. This is working perfectly as of right now. Except that there are no displacement events coming in. Even though other events, such as appearence, packets and keep-alive are getting through.

Try to search the code base for where these events are fired from, but did not found any indication as where to look.

Is it possible to get these displacement events?

**Comment by jeffyactive** [comment]
Hi @svenvanhees,

barnowl-aruba will not include the "events" property in the raddec output.  For this, you will need to combine with a [barnacles](https://github.com/reelyactive/barnacles/) instance, or, even easier, just use [Pareto Anywhere](https://github.com/reelyactive/pareto-anywhere/) which bundles barnowl-aruba & barnacles and some friendly web apps & visual APIs so you can test your setup out-of-the-box.

Kindly close the issue if that works for you.  Happy testing with your 303s!

**Comment by svenvanhees** [comment]
Perfect! Barnacles does indeed include a displacement event if the RSSI pivots in strength between receivers. Many thanks!
